#[cfg(feature = "dev-context-only-utils")]
use qualifier_attr::qualifiers;
use {
    agave_votor_messages::consensus_message::CertificateType, parking_lot::RwLock,
    solana_clock::Slot, std::collections::HashMap,
};

/// Tracks which certificate types the node already has a valid cert for, shared between the BLS
/// sigverifier and the consensus pool so that the sigverifier can drop redundant incoming certs.
///
/// The boolean value records whether *we* generated the cert ourselves (`true`) or whether it was
/// merely sigverified after being received over the network (`false`).
#[derive(Default)]
pub struct CompletedCertTypes(RwLock<HashMap<CertificateType, bool>>);

impl CompletedCertTypes {
    /// Returns `Some(generated)` if the cert type is known, otherwise `None`.
    pub fn get_generated_status(&self, cert_type: &CertificateType) -> Option<bool> {
        self.0.read().get(cert_type).copied()
    }

    /// Records that the sigverifier has just verified a cert of `cert_type`.
    ///
    /// Returns `true` if a cert of this type was already known (i.e. the insert was redundant).
    /// If the cert was previously recorded as generated by us, that flag is preserved.
    pub fn insert_verified(&self, cert_type: CertificateType) -> bool {
        use std::collections::hash_map::Entry;
        match self.0.write().entry(cert_type) {
            Entry::Occupied(_) => true,
            Entry::Vacant(v) => {
                v.insert(false);
                false
            }
        }
    }

    /// Records that the consensus pool has generated a cert of `cert_type` itself.
    #[cfg_attr(feature = "dev-context-only-utils", qualifiers(pub))]
    pub(crate) fn insert_generated(&self, cert_type: CertificateType) {
        self.0.write().insert(cert_type, true);
    }

    /// Drops all entries for slots strictly older than `root_slot`.
    pub(crate) fn prune(&self, root_slot: Slot) {
        self.0.write().retain(|c, _| c.slot() >= root_slot);
    }
}
